version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.23:5432/encontrao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: public


