version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encontrao-api
    ports:
      - '9090:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA}
    networks:
      - minha_rede

  postgres:
    image: postgres:latest
    container_name: encontrao-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - encontrao_pg_data:/var/lib/postgresql/data
    networks:
      - minha_rede

volumes:
  encontrao_pg_data:

networks:
  minha_rede:
    driver: bridge
