version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '9090:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: F5224s18uyPDvi@qbf
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: public


